Tab:
  Header: '&6&lH2M Remake Public!'
  Footer: '  &f&lStore: &6&lshop.publich2mremake.com'
  Prefix:
    Owner: '&c&lOWNER &f'
    Dev: '&e&lDEV &f'
    Admin: '&2&lADMIN &f'
    Mod: '&a&lMOD &f'
    User: '&fPICKPOCKET &c'